pub mod atx_heading;
pub mod block_spacing;
pub mod code_fence;
pub mod final_newline;
pub mod heading_increment;
pub mod heading_style;
pub mod sentence_per_line;
pub mod single_h1;
pub mod trailing_whitespace;
